In [5]:
import pandas as pd

In [6]:
df = pd.read_json('raw_311.json')

In [7]:
df.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,cross_street_1,...,bbl,vehicle_type,descriptor_2,taxi_pick_up_location,bridge_highway_name,road_ramp,bridge_highway_segment,taxi_company_borough,bridge_highway_direction,due_date
0,70691427,2026-10-09T02:56:50.000,DOT,Department of Transportation,Street Condition,Pothole,11415.0,83 AVENUE,83 AVENUE,MURRAY AND CAROL BERGER WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70694569,2026-10-09T02:51:38.000,DOT,Department of Transportation,Street Condition,Pothole,11429.0,SPRINGFIELD BOULEVARD,SPRINGFIELD BOULEVARD,REV CHARLIE W MIXON WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,70696162,2026-10-09T02:51:10.000,DOT,Department of Transportation,Street Condition,Pothole,11413.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,70686872,2026-10-09T02:50:42.000,DOT,Department of Transportation,Street Condition,Pothole,11412.0,LINDEN BOULEVARD,LINDEN BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70688026,2026-10-09T01:35:35.000,NYPD,New York City Police Department,Abandoned Vehicle,With License Plate,11379.0,64-12 75 STREET,75 STREET,PENELOPE AVENUE,...,4.030340e+09,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.shape

(50000, 48)

In [9]:
df['unique_key'].duplicated().sum()

np.int64(1)

#creating duplicates purposely

In [10]:
dupes = df.sample(2000, random_state = 1)

df = pd.concat([df, dupes], ignore_index=True)

In [11]:
df.shape

(52000, 48)

In [12]:
df['unique_key'].duplicated().sum()

np.int64(2001)

#Fixing the date types

In [13]:
df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce')
df['closed_date'] = pd.to_datetime(df['closed_date'], errors='coerce')

In [14]:
df[['created_date','closed_date']].dtypes

created_date    datetime64[ns]
closed_date     datetime64[ns]
dtype: object

In [15]:
df[df['created_date'] == 'NaT']

#so basically all rows are converted correctly

Empty DataFrame
Columns: [unique_key, created_date, agency, agency_name, complaint_type, descriptor, incident_zip, incident_address, street_name, cross_street_1, cross_street_2, address_type, city, facility_type, status, resolution_description, resolution_action_updated_date, community_board, police_precinct, borough, open_data_channel_type, park_facility_name, park_borough, closed_date, intersection_street_1, intersection_street_2, council_district, x_coordinate_state_plane, y_coordinate_state_plane, latitude, longitude, location, :@computed_region_f5dn_yrer, :@computed_region_yeji_bk3q, :@computed_region_sbqj_enih, :@computed_region_92fq_4b7q, location_type, landmark, bbl, vehicle_type, descriptor_2, taxi_pick_up_location, bridge_highway_name, road_ramp, bridge_highway_segment, taxi_company_borough, bridge_highway_direction, due_date]
Index: []

[0 rows x 48 columns]

In [16]:
df_sorted = df.sort_values(by = 'created_date', ascending = False)

In [17]:
df_latest = df_sorted.drop_duplicates(subset = ['unique_key'], keep='first')

In [18]:
df_latest.shape

(49999, 48)

In [19]:
df_latest['unique_key'].duplicated().sum()

np.int64(0)

In [20]:
df['status'].value_counts()

status
Closed         31881
Open           11641
In Progress     8328
Assigned         136
Pending            8
Unspecified        6
Name: count, dtype: int64

#Test Examples

In [21]:
#Test Example

small = pd.DataFrame({
    "unique_key": [1, 1, 2, 2],
    "status": ["Pending", "Closed", "Open", "Closed"],
    "created_date": pd.to_datetime(["2026-01-01", "2026-01-05", "2026-02-01", "2026-02-03"])
})
print(small)

   unique_key   status created_date
0           1  Pending   2026-01-01
1           1   Closed   2026-01-05
2           2     Open   2026-02-01
3           2   Closed   2026-02-03

In [23]:
small.sort_values(by = 'created_date', ascending = False).drop_duplicates(subset = ['unique_key'], keep = 'first')

   unique_key  status created_date
3           2  Closed   2026-02-03
1           1  Closed   2026-01-05

In [24]:
test = df.sample(1000)

In [26]:
test['status'] = 'TEST_NEWER_VERSION'
test['created_date'] = test['created_date'] + pd.Timedelta(days=1)

In [28]:
df_test = pd.concat([df,test], ignore_index=True)

In [29]:
df_test.shape

(53000, 48)

In [31]:
df_test_latest = df_test.sort_values(by = 'created_date' , ascending=False).drop_duplicates(subset = ['unique_key'], keep = 'first')

In [35]:
(df_test_latest['status'] == 'TEST_NEWER_VERSION').sum()

np.int64(999)

In [36]:
df_test_latest['unique_key'].is_unique

True

#Done with Testing

In [39]:
df_latest.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,cross_street_1,...,bbl,vehicle_type,descriptor_2,taxi_pick_up_location,bridge_highway_name,road_ramp,bridge_highway_segment,taxi_company_borough,bridge_highway_direction,due_date
0,70691427,2026-10-09 02:56:50,DOT,Department of Transportation,Street Condition,Pothole,11415.0,83 AVENUE,83 AVENUE,MURRAY AND CAROL BERGER WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70694569,2026-10-09 02:51:38,DOT,Department of Transportation,Street Condition,Pothole,11429.0,SPRINGFIELD BOULEVARD,SPRINGFIELD BOULEVARD,REV CHARLIE W MIXON WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,70696162,2026-10-09 02:51:10,DOT,Department of Transportation,Street Condition,Pothole,11413.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,70686872,2026-10-09 02:50:42,DOT,Department of Transportation,Street Condition,Pothole,11412.0,LINDEN BOULEVARD,LINDEN BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70688026,2026-10-09 01:35:35,NYPD,New York City Police Department,Abandoned Vehicle,With License Plate,11379.0,64-12 75 STREET,75 STREET,PENELOPE AVENUE,...,4.030340e+09,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
print(df_latest['created_date'].min())
print(df_latest['created_date'].max())
print(df_latest['created_date'].nunique())

2026-10-04 14:01:45
2026-10-09 02:56:50
41042

In [41]:
df_latest['agency'].value_counts()

agency
NYPD     21011
HPD      11837
DSNY      4153
DOT       3920
DEP       2789
DPR       1787
DOHMH     1259
DHS       1226
DOB       1111
TLC        427
DCWP       328
EDC         82
OOS         67
OTI          2
Name: count, dtype: int64

In [42]:
df_latest['complaint_type'].value_counts()

complaint_type
Illegal Parking                         8868
Noise - Residential                     4022
HEAT/HOT WATER                          2845
Blocked Driveway                        2542
UNSANITARY CONDITION                    2387
                                        ...
DEP Street Condition                       1
Special Natural Area District (SNAD)       1
Beach/Pool/Sauna Complaint                 1
Municipal Parking Facility                 1
Lifeguard                                  1
Name: count, Length: 153, dtype: int64

#Block 1: Cleaning

In [43]:
df_latest[['created_date','closed_date']].dtypes

created_date    datetime64[ns]
closed_date     datetime64[ns]
dtype: object

In [44]:
df_latest['closed_date'].isna().sum()

np.int64(18274)

In [45]:
df_latest['borough'].value_counts()

borough
BROOKLYN         16594
QUEENS           11654
MANHATTAN        10520
BRONX             9130
STATEN ISLAND     2036
Unspecified         65
Name: count, dtype: int64

In [46]:
df_latest['borough'] = df_latest['borough'].str.upper()
df_latest['agency'] = df_latest['agency'].str.upper()
df_latest['complaint_type'] = df_latest['complaint_type'].str.upper()

df_latest['borough'] = df_latest['borough'].str.strip()
df_latest['agency'] = df_latest['agency'].str.strip()
df_latest['complaint_type'] = df_latest['complaint_type'].str.strip()

/tmp/ipykernel_2489/1712058358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['borough'] = df_latest['borough'].str.upper()
/tmp/ipykernel_2489/1712058358.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['agency'] = df_latest['agency'].str.upper()
/tmp/ipykernel_2489/1712058358.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['complaint_type'] = df_latest['complaint_type'].str.upper()
/tmp/ipykernel_2489/1712058358.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['borough'] = df_latest['borough'].str.strip()
/tmp/ipykernel_2489/1712058358.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['agency'] = df_latest['agency'].str.strip()
/tmp/ipykernel_2489/1712058358.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['complaint_type'] = df_latest['complaint_type'].str.strip()

In [47]:
df_latest['borough'].value_counts(dropna=False)

borough
BROOKLYN         16594
QUEENS           11654
MANHATTAN        10520
BRONX             9130
STATEN ISLAND     2036
UNSPECIFIED         65
Name: count, dtype: int64

In [ ]:
#Create a days to close column

In [51]:
df_latest['days_to_close'] = (df_latest['closed_date'] - df_latest['created_date']).dt.total_seconds()/ 86400

/tmp/ipykernel_2489/3568052981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['days_to_close'] = (df_latest['closed_date'] - df_latest['created_date']).dt.total_seconds()/ 86400

In [52]:
df_latest['days_to_close'].describe()

count    31725.000000
mean         0.367583
std          0.609911
min         -1.001389
25%          0.028449
50%          0.089363
75%          0.398229
max          4.240880
Name: days_to_close, dtype: float64

In [54]:
len(df_latest)

49999

#Task 1: Handle the negative values

In [60]:
import numpy as np

In [56]:
neg = df_latest['days_to_close'] < 0
print('Negative rows', neg.sum())

Negative rows 37

In [61]:
df_latest.loc[neg,'days_to_close'] = np.nan

In [62]:
print(df_latest['days_to_close'].min())

0.0

#Task 2: Top 10 complaint types

In [64]:
df_latest['complaint_type'].value_counts().head(10)

complaint_type
ILLEGAL PARKING            8868
NOISE - RESIDENTIAL        4022
HEAT/HOT WATER             2845
BLOCKED DRIVEWAY           2542
UNSANITARY CONDITION       2387
NOISE - STREET/SIDEWALK    1777
STREET CONDITION           1329
PLUMBING                   1201
NOISE                      1104
PAINT/PLASTER              1091
Name: count, dtype: int64

# Task 3: Complaints per borough

In [66]:
df_latest['borough'].value_counts()

borough
BROOKLYN         16594
QUEENS           11654
MANHATTAN        10520
BRONX             9130
STATEN ISLAND     2036
UNSPECIFIED         65
Name: count, dtype: int64

#Task 5: Percent of complaints still open, per borough

In [67]:
df_latest['is_open'] = df_latest['closed_date'].isna()

/tmp/ipykernel_2489/2647332720.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_latest['is_open'] = df_latest['closed_date'].isna()

In [69]:
df_latest.groupby('borough')['is_open'].mean()*100

borough
BRONX            41.139102
BROOKLYN         36.760275
MANHATTAN        38.735741
QUEENS           30.719066
STATEN ISLAND    35.461690
UNSPECIFIED      63.076923
Name: is_open, dtype: float64

In [71]:
df_latest.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,cross_street_1,...,descriptor_2,taxi_pick_up_location,bridge_highway_name,road_ramp,bridge_highway_segment,taxi_company_borough,bridge_highway_direction,due_date,days_to_close,is_open
0,70691427,2026-10-09 02:56:50,DOT,Department of Transportation,STREET CONDITION,Pothole,11415.0,83 AVENUE,83 AVENUE,MURRAY AND CAROL BERGER WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,70694569,2026-10-09 02:51:38,DOT,Department of Transportation,STREET CONDITION,Pothole,11429.0,SPRINGFIELD BOULEVARD,SPRINGFIELD BOULEVARD,REV CHARLIE W MIXON WAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False
2,70696162,2026-10-09 02:51:10,DOT,Department of Transportation,STREET CONDITION,Pothole,11413.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False
3,70686872,2026-10-09 02:50:42,DOT,Department of Transportation,STREET CONDITION,Pothole,11412.0,LINDEN BOULEVARD,LINDEN BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False
4,70688026,2026-10-09 01:35:35,NYPD,New York City Police Department,ABANDONED VEHICLE,With License Plate,11379.0,64-12 75 STREET,75 STREET,PENELOPE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True